# Generated by Django 5.1.5 on 2025-04-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.TextField(),
        ),
    ]
