# Generated by Django 5.1.5 on 2025-04-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='profile',
        ),
    ]
